import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import BodySection from "@/components/BodySection";
import PopularQuestions from "@/components/PopularQuestions";
import { BsChevronRight } from "react-icons/bs";
import brandImg from "../public/assets/brand.jpg";
import logoNetflix from "../public/assets/logoN.png";
import tv from "../public/assets/tv.png";
import FormSection from "@/components/FormSection";
import Footer from "@/components/Footer";

export default function Home({ body, questions, links }) {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-black position-relative">
        {/* NEWS INFO */}
        <div className="bg-white d-flex gap-3 justify-content-center align-items-center p-3 mb-3">
          <span
            className="px-1 py-0 text-white rounded"
            style={{ background: "red" }}
          >
            NOVIDADE!
          </span>
          <span>
            Planos a partir de <span className="fs-5 fw-700">R$18,90.</span>
          </span>
          <span className="d-flex align-items-center" style={{fontSize: "14px"}}>
            <a href="" className="text-decoration-none">
              Sabia mais
            </a>
            <BsChevronRight className="fw-800" />
          </span>
        </div>

        {/* HEADER BRAND */}
        <div
          className="position-relative"
          style={{ maxHeight: "90vh", overflow: "hidden"}}
        >
          <Image style={{ maxHeight: "100vh" }} alt="logo" src={brandImg} className="" priority />
          <div
            className="position-absolute top-0 start-0 d-flex flex-column justify-content-center"
            style={{
              height: "100%",
              width: "100%",
              background: "linear-gradient(rgba(0, 0, 0,0.9), rgba(0, 7, 26, .8))",
            }}
          >
            <header className="position-absolute top-0 d-flex justify-content-between w-100 align-items-center px-3 py-3 px-lg-5">
              <div style={{ width: "30%" }}>
                <Image width='150' src={logoNetflix} alt="logo" className='logo' />
              </div>
              <div className="d-flex gap-1">
                <div className="">
                  <select className="bg-transparent fs-6 text-white align-center rounded border-white py-2">
                    <option value="1">Português</option>
                    <option value="2">English</option>
                    <option value="3">Français</option>
                  </select>
                </div>
                <button
                  className="btn text-white"
                  style={{ background: "red" }}
                  onClick={() => router.push("/login")}
                >
                  Entrar
                </button>
              </div>
            </header>
            <div className="d-flex px-3 flex-column gap-1 justify-content-center align-items-center text-white">
              <h1
                style={{ fontSize: "270%", fontWeight: "700" }}
                className=""
              >
                Filmes, séries e muito mais. Sem limites
              </h1>
              <p className="fs-6" style={{fontWeight: "600"}}>
                Assista onde quiser. Cancele quando quiser.
              </p>
              <div className="">
                <FormSection />
              </div>
            </div>
          </div>
        </div>

        {/* BODY SECTION */}
        <div
          className="global-body position-absolute px-3 px-md-5"
        >
          <BodySection body={body} url={tv} />
          <div className="foot-section">
            <PopularQuestions questions={questions} />
            <FormSection />
            <Footer links={links} />
          </div>
        </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await import("./api/body.json");
  const questions = await import("./api/questions.json");
  const links = await import("./api/links.json");

  return {
    props: {
      body: data.body,
      questions: questions.questionsPopular,
      links: links.links,
    },
  };
}
